### ISSUE TITLE
Transparency issues at extreme angles

### ISSUE THREAD

**Issue by isXander** [MCRcortex/nvidium#11]
![javaw_rbqzXZ0RwV](https://user-images.githubusercontent.com/43245524/234875764-3c39da17-3d68-4562-bb4c-43cea640b7b8.png)
notice the grass.

**Comment by isXander** [comment]
may not be a transparency issue. 
![javaw_4nLvcWLGGZ](https://user-images.githubusercontent.com/43245524/234876018-2631533d-a3aa-41dd-954b-f0583b8c382c.png)

**Comment by isXander** [comment]
very apparent here. 
![javaw_1rZYKoIPpM](https://user-images.githubusercontent.com/43245524/234876257-6d82245c-5b6a-4009-b42c-54a414f8e29f.jpg)

**Comment by MCRcortex** [comment]
Is this with mip maps enabled? if so, yea, all textures use the same mipping (even ones that shouldent) should be fixed in the next release of sodium, temporary fix is to disable mipmapping

**Comment by isXander** [comment]
Yes this is with mip mapping.

**Comment by Owehttamy** [comment]
It still occurs with and without mipmaps enabled on Sodium [0.4.11 (Beta)](https://modrinth.com/mod/sodium/version/mc1.19.4-0.4.11).

**Comment by lymboofficial** [comment]
Still running into this issue on version 1.20.1.
![2023-06-22_18 40 10](https://github.com/MCRcortex/nvidium/assets/72504709/e9dbc450-4e5a-4f23-ac8a-4d92861d9249)
![2023-06-22_18 40 38](https://github.com/MCRcortex/nvidium/assets/72504709/ddadb44a-b5f1-4a40-ba08-1b99152a0859)
![2023-06-22_18 41 29](https://github.com/MCRcortex/nvidium/assets/72504709/18f32248-3b32-4a3d-bd2f-da6f7821f0ff)

**Comment by MCRcortex** [comment]
This should no longer be an issue in the latest versions
