### ISSUE TITLE
Delay in breaking blocks with Nvidium enabled

### ISSUE THREAD

**Issue by nmackowiakk** [MCRcortex/nvidium#156]
https://github.com/MCRcortex/nvidium/assets/111523952/850502d3-31ce-4bc7-82cd-c90430bed6dd

This kind of delay doesn't appear with nvidium disabled.

**Comment by Westbrooke117** [comment]
I might be having the same issue. Are you using the mod Bobby?

**Comment by nmackowiakk** [comment]
I am! Is it what causes it?

**Comment by Westbrooke117** [comment]
I’ve found the issue can be remedied by changing the viewDistanceOverwrite setting in Bobby. Despite it saying it is for the Singleplayer internal server, it’s resolved the issues on the multiplayer server I was playing on too. I’ve found that changing the setting to the chunk distance of the server works. I’m unsure though whether it is Bobby or Nvidium which causes the issue.

**Comment by MiniGwynie** [comment]
i'm getting a delay on a lot of things, including breaking blocks. opening doors (especially with pressure plates) and placing beds are where it's most noticeable. i find it only happens when render distance is above 32. this is true for both bobby and farsight. disabling singleplayer server view distance/view distance overwrite in bobby fixes it, but that also disables rendering beyond 32 chunks, at least in singleplayer. this can happen at 20 tps 200+ fps. limiting fps had no effect.

this bug does not happen when render distance is above 32 without nvidium, so this issue is specific to nvidium. i also tested with no other mods, of course.

i've had this issue in Minecraft version 1.20.4, fabric version 0.15.6, fabric api versions 0.95.4 and 0.96.1, nvidium versions 0.2.6 and 0.2.5. i'm going to try testing every version of nvidium, then every version of everything else that was made while the earliest version of nvidium existed for 1.20.4, then everything as up to date as i can get them. i will post another reply with my results if i still have enough spirit to continue existing after putting in that much effort for almost certain disappointment.

**Comment by Westbrooke117** [comment]
I am playing on 1.20.4 with the relevant mods being:
- Nvidium 0.2.6-beta
- Sodium 0.5.8
- Fabric API 0.96.1
- Bobby 5.1.0

Nvidium and Sodium are on the default settings with no advanced settings changed, and here is my Bobby config:
![image](https://github.com/MCRcortex/nvidium/assets/93863049/aaa402bd-0e61-4582-b36e-522451f14a7e)

Here is a Singleplayer world I just created with Bobby and Nvidium at 64 chunks. There was no block or entity lag observed:
![image](https://github.com/MCRcortex/nvidium/assets/93863049/425e9e39-9e3d-4f82-a221-58f6a1ab6aa8)

**Comment by MiniGwynie** [comment]
the issue gets worse as more chunks load. increasing memory doesn't help. issue persists on nvidium 0.2.4, sodium 0.5.4, fabric api 0.96.1, fabric 0.15.6. setting the server render distance to 1 in bobby reduces the issue but doesn't eliminate it. i'm going to try to replicate the conditions in the image above to try and isolate the issue.

**Comment by MiniGwynie** [comment]
i made a new 1.20.4 fabric profile in my mod manager, downloaded the mods below and replicated the settings shown and described in the post above. the issue persisted. the issue was probably less pronounced for the person above due to the server render distance being set to 12.

driver version (sanity check): 545.92

mods: 
fabric 0.15.6
betterf3 9.0.0
bobby 5.1.0
cloth config api 13.0.121
fabric api 0.96.1
sodium 0.5.8
nvidium 0.2.6
mod menu: 9.0.0

my bobby settings:
![bobby](https://github.com/MCRcortex/nvidium/assets/136741983/ea5d0cb0-0f05-4eb3-8c29-414118813fd4)

my general settings:
![general](https://github.com/MCRcortex/nvidium/assets/136741983/f5b5c124-aba7-4c6c-9215-f4b543c2a6ab)

my nvidium settings:
![nvidium](https://github.com/MCRcortex/nvidium/assets/136741983/48b6af0a-481d-4da3-b247-8e6b33e35971)

the door issue + f3:
![door](https://github.com/MCRcortex/nvidium/assets/136741983/4b704ba5-1e6b-400e-968c-6d52a161cc5e)

**Comment by MiniGwynie** [comment]
sanity check: updated graphics driver, no effect

**Comment by MiniGwynie** [comment]
https://github.com/MCRcortex/nvidium/issues/141

seems related

**Comment by CoopersHyper** [comment]
> the issue gets worse as more chunks load. increasing memory doesn't help. issue persists on nvidium 0.2.4, sodium 0.5.4, fabric api 0.96.1, fabric 0.15.6. setting the server render distance to 1 in bobby reduces the issue but doesn't eliminate it. i'm going to try to replicate the conditions in the image above to try and isolate the issue.

Contrary to what you may think, increasing the memory actually makes it worse. Me being me, whenever i first got the mod I whacked up the max memory at far as it could go. I enabled the automatic memory limit and my problem is solved. If you still are experiencing some issues, I would try manually setting the limit to 3/4 or even 1/2 or your GPU's memory.

Hope this helps!

**Comment by noahnao** [comment]
> I’ve found the issue can be remedied by changing the viewDistanceOverwrite setting in Bobby. Despite it saying it is for the Singleplayer internal server, it’s resolved the issues on the multiplayer server I was playing on too. I’ve found that changing the setting to the chunk distance of the server works. I’m unsure though whether it is Bobby or Nvidium which causes the issue.

This did absolutely nothing for me. I set my server render distance to 75 and my client render distance to 75, as well as setting bobby max render distance to 75, and the issue still persisted.

**Comment by Briarbot2011** [comment]
> > I’ve found the issue can be remedied by changing the viewDistanceOverwrite setting in Bobby. Despite it saying it is for the Singleplayer internal server, it’s resolved the issues on the multiplayer server I was playing on too. I’ve found that changing the setting to the chunk distance of the server works. I’m unsure though whether it is Bobby or Nvidium which causes the issue.
> 
> This did absolutely nothing for me. I set my server render distance to 75 and my client render distance to 75, as well as setting bobby max render distance to 75, and the issue still persisted.

the way i found to resolve the issue is to turn off automatic memory limit and manually set the max memory to at or a bit below your gpu's vram in binary MB(meaning 1 GB is equal to 1024 MB)

**Comment by noahnao** [comment]
> > > I’ve found the issue can be remedied by changing the viewDistanceOverwrite setting in Bobby. Despite it saying it is for the Singleplayer internal server, it’s resolved the issues on the multiplayer server I was playing on too. I’ve found that changing the setting to the chunk distance of the server works. I’m unsure though whether it is Bobby or Nvidium which causes the issue.
> > 
> > 
> > This did absolutely nothing for me. I set my server render distance to 75 and my client render distance to 75, as well as setting bobby max render distance to 75, and the issue still persisted.
> 
> the way i found to resolve the issue is to turn off automatic memory limit and manually set the max memory to at or a bit below your gpu's vram in binary MB(meaning 1 GB is equal to 1024 MB)

Thanks for sharing your solution! Unfortunately, I tried setting the max memory to 9216 MB as you suggested, but it didn't resolve the issue for me. I have an RTX 3080 with 10GB of VRAM, so I followed your advice closely. However, the problem persisted.
The only workaround that seems to work for me is turning down the render distance to vanilla, which defeats the purpose of the mod entirely. It's frustrating because the whole point of using the mod is to enjoy larger render distances. I'm still searching for a solution that allows me to utilize the mod to its full potential without encountering this issue.
If you or anyone else has any further suggestions, I'm all ears!

**Comment by Briarbot2011** [comment]
> > > > I’ve found the issue can be remedied by changing the viewDistanceOverwrite setting in Bobby. Despite it saying it is for the Singleplayer internal server, it’s resolved the issues on the multiplayer server I was playing on too. I’ve found that changing the setting to the chunk distance of the server works. I’m unsure though whether it is Bobby or Nvidium which causes the issue.
> > > 
> > > 
> > > This did absolutely nothing for me. I set my server render distance to 75 and my client render distance to 75, as well as setting bobby max render distance to 75, and the issue still persisted.
> > 
> > 
> > the way i found to resolve the issue is to turn off automatic memory limit and manually set the max memory to at or a bit below your gpu's vram in binary MB(meaning 1 GB is equal to 1024 MB)
> 
> Thanks for sharing your solution! Unfortunately, I tried setting the max memory to 9216 MB as you suggested, but it didn't resolve the issue for me. I have an RTX 3080 with 10GB of VRAM, so I followed your advice closely. However, the problem persisted. The only workaround that seems to work for me is turning down the render distance to vanilla, which defeats the purpose of the mod entirely. It's frustrating because the whole point of using the mod is to enjoy larger render distances. I'm still searching for a solution that allows me to utilize the mod to its full potential without encountering this issue. If you or anyone else has any further suggestions, I'm all ears!

these are the configs for my personal modpack that runs on 1.20.1: 
![image](https://github.com/MCRcortex/nvidium/assets/115622837/2d46a78d-a47c-4e72-8858-4b127bd0962e)
![image](https://github.com/MCRcortex/nvidium/assets/115622837/ebcf7557-2f82-4513-98e9-32849e327f6d)
![image](https://github.com/MCRcortex/nvidium/assets/115622837/ecfa64f7-fe2c-4e0e-ac0a-ff73b12f8e04)

**Comment by noahnao** [comment]
> > > > > I’ve found the issue can be remedied by changing the viewDistanceOverwrite setting in Bobby. Despite it saying it is for the Singleplayer internal server, it’s resolved the issues on the multiplayer server I was playing on too. I’ve found that changing the setting to the chunk distance of the server works. I’m unsure though whether it is Bobby or Nvidium which causes the issue.
> 
> > > > 
> 
> > > > 
> 
> > > > This did absolutely nothing for me. I set my server render distance to 75 and my client render distance to 75, as well as setting bobby max render distance to 75, and the issue still persisted.
> 
> > > 
> 
> > > 
> 
> > > the way i found to resolve the issue is to turn off automatic memory limit and manually set the max memory to at or a bit below your gpu's vram in binary MB(meaning 1 GB is equal to 1024 MB)
> 
> > 
> 
> > Thanks for sharing your solution! Unfortunately, I tried setting the max memory to 9216 MB as you suggested, but it didn't resolve the issue for me. I have an RTX 3080 with 10GB of VRAM, so I followed your advice closely. However, the problem persisted. The only workaround that seems to work for me is turning down the render distance to vanilla, which defeats the purpose of the mod entirely. It's frustrating because the whole point of using the mod is to enjoy larger render distances. I'm still searching for a solution that allows me to utilize the mod to its full potential without encountering this issue. If you or anyone else has any further suggestions, I'm all ears!
> 
> 
> 
> these are the configs for my personal modpack that runs on 1.20.1: 
> 
> ![image](https://github.com/MCRcortex/nvidium/assets/115622837/2d46a78d-a47c-4e72-8858-4b127bd0962e)
> 
> ![image](https://github.com/MCRcortex/nvidium/assets/115622837/ebcf7557-2f82-4513-98e9-32849e327f6d)
> 
> ![image](https://github.com/MCRcortex/nvidium/assets/115622837/ecfa64f7-fe2c-4e0e-ac0a-ff73b12f8e04)
> 
> 

I want a renderdistance larger than 32 chunks, without bugs. I am well aware that if you turn the viewdistance down to vanilla values, the bug goes away. It should be possible to run above 32 chunk renderdistance, that is why this is an issue. I know the developer is working on it, but it might be an issue with Bobby, not Nvidium.

**Comment by JoeyHamlet** [comment]
> > > > > > I’ve found the issue can be remedied by changing the viewDistanceOverwrite setting in Bobby. Despite it saying it is for the Singleplayer internal server, it’s resolved the issues on the multiplayer server I was playing on too. I’ve found that changing the setting to the chunk distance of the server works. I’m unsure though whether it is Bobby or Nvidium which causes the issue.
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > This did absolutely nothing for me. I set my server render distance to 75 and my client render distance to 75, as well as setting bobby max render distance to 75, and the issue still persisted.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > the way i found to resolve the issue is to turn off automatic memory limit and manually set the max memory to at or a bit below your gpu's vram in binary MB(meaning 1 GB is equal to 1024 MB)
> > 
> > 
> > > 
> > 
> > 
> > > Thanks for sharing your solution! Unfortunately, I tried setting the max memory to 9216 MB as you suggested, but it didn't resolve the issue for me. I have an RTX 3080 with 10GB of VRAM, so I followed your advice closely. However, the problem persisted. The only workaround that seems to work for me is turning down the render distance to vanilla, which defeats the purpose of the mod entirely. It's frustrating because the whole point of using the mod is to enjoy larger render distances. I'm still searching for a solution that allows me to utilize the mod to its full potential without encountering this issue. If you or anyone else has any further suggestions, I'm all ears!
> > 
> > 
> > these are the configs for my personal modpack that runs on 1.20.1:
> > ![image](https://private-user-images.githubusercontent.com/115622837/323328887-2d46a78d-a47c-4e72-8858-4b127bd0962e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNjI5OTgsIm5iZiI6MTcxNTM2MjY5OCwicGF0aCI6Ii8xMTU2MjI4MzcvMzIzMzI4ODg3LTJkNDZhNzhkLWE0N2MtNGU3Mi04ODU4LTRiMTI3YmQwOTYyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxNzM4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDg3NjVhYzVlNDE3OTM3NjY1ZmNjNjI3NmUxMjIzY2JmMzliMDVkM2Y4YmIwMWMwMzZkMzhkNTAzOTNlOTVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F0pD2VCB-lL0tc-0M2yqiQ-MjuqSzCm36EeV2YwlvOM)
> > ![image](https://private-user-images.githubusercontent.com/115622837/323329284-ebcf7557-2f82-4513-98e9-32849e327f6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNjI5OTgsIm5iZiI6MTcxNTM2MjY5OCwicGF0aCI6Ii8xMTU2MjI4MzcvMzIzMzI5Mjg0LWViY2Y3NTU3LTJmODItNDUxMy05OGU5LTMyODQ5ZTMyN2Y2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxNzM4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDIxMGIwZjhiNzc4ZDEwMGJjMzMzZWI5YWNjMDBhMzgyMTY1NmRjMTk3NjgyYjljN2IzMTgxYzA2ZWZiYjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.buuJ1C_HzX2DFwQfseopdr0sTJY9_ZfWHYNI6w2W19g)
> > ![image](https://private-user-images.githubusercontent.com/115622837/323329436-ecfa64f7-fe2c-4e0e-ac0a-ff73b12f8e04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNjI5OTgsIm5iZiI6MTcxNTM2MjY5OCwicGF0aCI6Ii8xMTU2MjI4MzcvMzIzMzI5NDM2LWVjZmE2NGY3LWZlMmMtNGUwZS1hYzBhLWZmNzNiMTJmOGUwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxNzM4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGUzZWUwOGJkMDg5NWExZTM5MDI2Zjg0YTU5MTQ0YzE4YTQyNGZmMjQxNDBiNmRlYzY2NTAyZDNmM2JlOWJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Zyw4MdFOb71LxGYL5K1XPOwwVWjUtgKX20bYsAp7y1U)
> 
> I want a renderdistance larger than 32 chunks, without bugs. I am well aware that if you turn the viewdistance down to vanilla values, the bug goes away. It should be possible to run above 32 chunk renderdistance, that is why this is an issue. I know the developer is working on it, but it might be an issue with Bobby, not Nvidium.

I believe it wouldn't be an issue with Bobby as from what I understand you're playing in singleplayer. Bobby doesn't come into effect in singleplayer unless you put the "Singleplayer Server View Distance" to anything above 0. Otherwise the "Max Render Distance" esentially only extends the range of the render distance slider in sodium. If you do have Single player view distance set to any other value it does "solve" the issue, but it does so at the expense of not loading any chunks beyond the set view distance in bobby's config.

**Comment by noahnao** [comment]
> > > > > > > I’ve found the issue can be remedied by changing the viewDistanceOverwrite setting in Bobby. Despite it saying it is for the Singleplayer internal server, it’s resolved the issues on the multiplayer server I was playing on too. I’ve found that changing the setting to the chunk distance of the server works. I’m unsure though whether it is Bobby or Nvidium which causes the issue.
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > This did absolutely nothing for me. I set my server render distance to 75 and my client render distance to 75, as well as setting bobby max render distance to 75, and the issue still persisted.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > the way i found to resolve the issue is to turn off automatic memory limit and manually set the max memory to at or a bit below your gpu's vram in binary MB(meaning 1 GB is equal to 1024 MB)
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Thanks for sharing your solution! Unfortunately, I tried setting the max memory to 9216 MB as you suggested, but it didn't resolve the issue for me. I have an RTX 3080 with 10GB of VRAM, so I followed your advice closely. However, the problem persisted. The only workaround that seems to work for me is turning down the render distance to vanilla, which defeats the purpose of the mod entirely. It's frustrating because the whole point of using the mod is to enjoy larger render distances. I'm still searching for a solution that allows me to utilize the mod to its full potential without encountering this issue. If you or anyone else has any further suggestions, I'm all ears!
> 
> > > 
> 
> > > 
> 
> > > these are the configs for my personal modpack that runs on 1.20.1:
> 
> > > ![image](https://private-user-images.githubusercontent.com/115622837/323328887-2d46a78d-a47c-4e72-8858-4b127bd0962e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNjI5OTgsIm5iZiI6MTcxNTM2MjY5OCwicGF0aCI6Ii8xMTU2MjI4MzcvMzIzMzI4ODg3LTJkNDZhNzhkLWE0N2MtNGU3Mi04ODU4LTRiMTI3YmQwOTYyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxNzM4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDg3NjVhYzVlNDE3OTM3NjY1ZmNjNjI3NmUxMjIzY2JmMzliMDVkM2Y4YmIwMWMwMzZkMzhkNTAzOTNlOTVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F0pD2VCB-lL0tc-0M2yqiQ-MjuqSzCm36EeV2YwlvOM)
> 
> > > ![image](https://private-user-images.githubusercontent.com/115622837/323329284-ebcf7557-2f82-4513-98e9-32849e327f6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNjI5OTgsIm5iZiI6MTcxNTM2MjY5OCwicGF0aCI6Ii8xMTU2MjI4MzcvMzIzMzI5Mjg0LWViY2Y3NTU3LTJmODItNDUxMy05OGU5LTMyODQ5ZTMyN2Y2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxNzM4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDIxMGIwZjhiNzc4ZDEwMGJjMzMzZWI5YWNjMDBhMzgyMTY1NmRjMTk3NjgyYjljN2IzMTgxYzA2ZWZiYjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.buuJ1C_HzX2DFwQfseopdr0sTJY9_ZfWHYNI6w2W19g)
> 
> > > ![image](https://private-user-images.githubusercontent.com/115622837/323329436-ecfa64f7-fe2c-4e0e-ac0a-ff73b12f8e04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNjI5OTgsIm5iZiI6MTcxNTM2MjY5OCwicGF0aCI6Ii8xMTU2MjI4MzcvMzIzMzI5NDM2LWVjZmE2NGY3LWZlMmMtNGUwZS1hYzBhLWZmNzNiMTJmOGUwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxNzM4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OGUzZWUwOGJkMDg5NWExZTM5MDI2Zjg0YTU5MTQ0YzE4YTQyNGZmMjQxNDBiNmRlYzY2NTAyZDNmM2JlOWJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Zyw4MdFOb71LxGYL5K1XPOwwVWjUtgKX20bYsAp7y1U)
> 
> > 
> 
> > I want a renderdistance larger than 32 chunks, without bugs. I am well aware that if you turn the viewdistance down to vanilla values, the bug goes away. It should be possible to run above 32 chunk renderdistance, that is why this is an issue. I know the developer is working on it, but it might be an issue with Bobby, not Nvidium.
> 
> 
> 
> I believe it wouldn't be an issue with Bobby as from what I understand you're playing in singleplayer. Bobby doesn't come into effect in singleplayer unless you put the "Singleplayer Server View Distance" to anything above 0. Otherwise the "Max Render Distance" esentially only extends the range of the render distance slider in sodium. If you do have Single player view distance set to any other value it does "solve" the issue, but it does so at the expense of not loading any chunks beyond the set view distance in bobby's config. 

No i am not on single player.

**Comment by JoeyHamlet** [comment]
> No i am not on single player.

Ah, nvm. I should have paid more attention to your earlier comments.

**Comment by RomanSonnik** [comment]
![image](https://github.com/MCRcortex/nvidium/assets/116032351/276ac5b2-b694-4e7c-af68-1dabf1c74a91)
Does somebody knows how to unlock this setting? Thanks.

**Comment by CoopersHyper** [comment]
Disable “Automatic memory limit”

**Comment by CoopersHyper** [comment]
> ![image](https://private-user-images.githubusercontent.com/116032351/346192625-276ac5b2-b694-4e7c-af68-1dabf1c74a91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDExOTYsIm5iZiI6MTcyMDIwMDg5NiwicGF0aCI6Ii8xMTYwMzIzNTEvMzQ2MTkyNjI1LTI3NmFjNWIyLWI2OTQtNGU3Yy1hZjY4LTFkYWJmMWM3NGE5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNVQxNzM0NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmY5NTc4OTIxODJjMTUyZWU2YjJjMDgxODJhZmIwMGIwMmU3MTkxNTViZjQ4MDIzMzRhNmYwZjk3NzM5ZDg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._gsYrqvLVgoNTUECj-gut-DMk1JRJwOE5TYjL_52ptc) Does somebody knows how to unlock this setting? Thanks.

Disable “Automatic memory limit”

**Comment by gabepikamole** [comment]
having the same issue. will try solutions and update to tell people whether it's fixable still or not.

**Comment by fasscass** [comment]
I have the same issue, also using bobby. Using Nvidium 0.3.1 in 1.21.1 in an online server. Solutions shown here didn't change anything. I tried changing transparency settings but none changed anything either
